### ISSUE TITLE
React.Suspense is broken

### ISSUE THREAD

**Issue by Hypnosphi** [wojtekmaj/enzyme-adapter-react-17#1]
Whenever I mount a tree with React.Suspense, it throws:

```
Error: Enzyme Internal Error: unknown node with tag 23

    at _toTree (/Users/jetbrains/IdeaProjects/TeamCity/react-ui/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:166:3)
    at childrenToTree (/Users/jetbrains/IdeaProjects/TeamCity/react-ui/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:292:4)
```

Brief debugging showed that this probably is the new [`Offscreen`](https://github.com/facebook/react/pull/18729) fiber type

**Comment by wojtekmaj** [comment]
Looks like we need to add something in `detectFiberTags.js`. But since Offscreen isn't exposed I have no clue on how to do this, hmmm...

**Comment by Hypnosphi** [comment]
Render `Suspence` and get the type of its only child?

**Comment by wojtekmaj** [comment]
@Hypnosphi can you try this? https://github.com/wojtekmaj/enzyme-adapter-react-17/pull/3
